root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["--addr=localhost:3000"]
  bin = "./tmp/main"
  cmd = "GOEXPERIMENT=loopvar go build -race -o ./tmp/main"
  delay = 1000
  # Exluding ent because it causes Air to infinitely detect changes
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "ent"]
  exclude_file = []
  exclude_regex = ["_test.go", ".*_templ.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = ["go generate ./..."]
  rerun = false
  rerun_delay = 1000
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
